name: CNK Release

on:
  push
concurrency:
  group: cataclysm-build
  cancel-in-progress: true
jobs:
  builds:
    runs-on: ubuntu-latest
    env:
        ZSTD_CLEVEL: 17
    steps:
      - uses: actions/checkout@v3
      - name: Get build timestamp
        id: get-timestamp
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY-MM-DD-HHmm'
      - name: Generate environmental variables
        id: generate_env_vars
        run: |
          echo "tag_name=cdda-experimental-${{ steps.get-timestamp.outputs.time }}" >> $GITHUB_OUTPUT
          echo "release_name=Cataclysm-DDA experimental build ${{ steps.get-timestamp.outputs.time }}" >> $GITHUB_OUTPUT
      - name: Set up JDK 8 (android)
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Build and Dependencies (android)
        run: |
          sudo apt-get update
          sudo apt-get install gettext unzip
      - name: sign
        working-directory: ./android
        run: | 
          keytool -genkey -keystore /tmp/a.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias a -dname "cn=a, ou=a, o=a, c=a" -storepass 123456 -keypass 123456
          echo -e "keyPassword=123456\nkeyAlias=a\nstorePassword=123456\nstoreFile=/tmp/a.keystore" > keystore.properties
      - name: cnk
        run: |
          wget https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/releases/latest/download/Kenan-Modpack-Mod.zip
          unzip Kenan-Modpack-Mod.zip
          cp -r Kenan-Modpack-Chinese/ data/mods/
      - name: udp
        run: |
          git clone https://github.com/Theawesomeboophis/UndeadPeopleTileset
          cd UndeadPeopleTileset/TILESETS
          cp -r UndeadPeopleTileset/TILESETS/* ./
      - uses: burrunan/gradle-cache-action@v1
        name: Build CDDA
        with:
         job-id: jdk8
         build-root-directory: ./android
         arguments: assembleExperimentalRelease --build-cache
         properties: |
          j=2
          abi_arm_32=false
      - name: move
        working-directory: ./android
        run:  mv ./app/build/outputs/apk/experimental/release/*.apk "/home/runner/work/Cataclysm-DDA/${{ steps.generate_env_vars.outputs.release_name }}.apk"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_env_vars.outputs.tag_name }}
          release_name: ${{ steps.generate_env_vars.outputs.release_name }}
          draft: false
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "/home/runner/work/Cataclysm-DDA/${{ steps.generate_env_vars.outputs.release_name }}.apk"
          asset_name: ${{ steps.generate_env_vars.outputs.release_name }}.apk
          asset_content_type: application/zip
