name: "Experimental Release"
concurrency: release
on:
  push:
    branches:
      - ad1

jobs:
  builds:
    runs-on: ubuntu-latest
    env:
        ZSTD_CLEVEL: 17
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 (android)
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Build and Dependencies (android)
        run: |
          sudo apt-get update
          sudo apt-get install gettext          
      - name: Build CDDA (android)
        working-directory: ./android
        run: | 
          chmod +x gradlew
          ./gradlew -Pj=$((`nproc`+0)) -Pabi_arm_32=false assembleExperimentalRelease
      - uses: actions/upload-artifact@v2
        with:
           name: Package
           path: android/app/build/outputs/apk/experimental/release/
         
           #path: app/build/outputs/
           #path: [MODULE]/build/outputs/
           retention-days: 2
